var searchData=
[
  ['channelmode',['ChannelMode',['../LEDController_8h.html#a00f0b242f777245ee33e575df3cfc4bc',1,'LEDController.h']]],
  ['clpusbserialbridge',['CLPUSBSerialBridge',['../classCLPUSBSerialBridge.html',1,'CLPUSBSerialBridge'],['../classCLPUSBSerialBridge.html#a955fbdd48589591ecf224806e4f2f0f4',1,'CLPUSBSerialBridge::CLPUSBSerialBridge()'],['../classCLPUSBSerialBridge.html#a0a3a530a8147d533a4554cad84e05dca',1,'CLPUSBSerialBridge::CLPUSBSerialBridge(const char *serialNumber)']]],
  ['command',['Command',['../structCommand.html',1,'']]],
  ['corsairlightingfirmware',['CorsairLightingFirmware',['../classCorsairLightingFirmware.html',1,'']]],
  ['corsairlightingnodepro',['CorsairLightingNodePRO',['../classCorsairLightingNodePRO.html',1,'']]],
  ['corsairlightingprotocol_2eh',['CorsairLightingProtocol.h',['../CorsairLightingProtocol_8h.html',1,'']]],
  ['corsairlightingprotocolcontroller',['CorsairLightingProtocolController',['../classCorsairLightingProtocolController.html',1,'CorsairLightingProtocolController'],['../classCorsairLightingProtocolController.html#ae5b62dededab9484da4fa50f6693f85e',1,'CorsairLightingProtocolController::CorsairLightingProtocolController(ILEDController *l, CorsairLightingFirmware *c)'],['../classCorsairLightingProtocolController.html#ab4d846f9da7051850cfdd0ac1990c797',1,'CorsairLightingProtocolController::CorsairLightingProtocolController(ILEDController *l, ITemperatureController *t, IFanController *f, CorsairLightingFirmware *c)']]],
  ['corsairlightingprotocolhid',['CorsairLightingProtocolHID',['../classCorsairLightingProtocolHID.html',1,'CorsairLightingProtocolHID'],['../classCorsairLightingProtocolHID.html#abb342574347d59f653f58775c3d4d4b6',1,'CorsairLightingProtocolHID::CorsairLightingProtocolHID(CorsairLightingProtocolController *controller)'],['../classCorsairLightingProtocolHID.html#af5c67b9e322610f7cf5ce94cff42c112',1,'CorsairLightingProtocolHID::CorsairLightingProtocolHID(CorsairLightingProtocolController *controller, const char *serialNumber)']]],
  ['corsairlightingprotocolresponse',['CorsairLightingProtocolResponse',['../classCorsairLightingProtocolResponse.html',1,'']]],
  ['corsairlightingprotocolserial',['CorsairLightingProtocolSerial',['../classCorsairLightingProtocolSerial.html',1,'CorsairLightingProtocolSerial'],['../classCorsairLightingProtocolSerial.html#ac8331a93dd8af688047830c8e2e5f839',1,'CorsairLightingProtocolSerial::CorsairLightingProtocolSerial()']]],
  ['corsair_20lighting_20protocol_20_5b_21_5barduino_2dlibrary_2dbadge_5d_28https_3a_2f_2fwww_2eardu_2dbadge_2ecom_2fbadge_2fcorsair_2520lighting_2520protocol_2esvg_3f_29_5d_28https_3a_2f_2fwww_2eardu_2dbadge_2ecom_2fcorsair_2520lighting_2520protocol_29_20_5b_21_5btest_20status_5d_28https_3a_2f_2fgithub_2ecom_2flegion2_2fcorsairlightingprotocol_2fworkflows_2ftest_2fbadge_2esvg_29_5d_28https_3a_2f_2fgithub_2ecom_2flegion2_2fcorsairlightingprotocol_2factions_3fquery_3dworkflow_253atest_2bbranch_253adev_2bevent_253apush_29',['Corsair Lighting Protocol [![arduino-library-badge](https://www.ardu-badge.com/badge/Corsair%20Lighting%20Protocol.svg?)](https://www.ardu-badge.com/Corsair%20Lighting%20Protocol) [![Test Status](https://github.com/Legion2/CorsairLightingProtocol/workflows/Test/badge.svg)](https://github.com/Legion2/CorsairLightingProtocol/actions?query=workflow%3ATest+branch%3Adev+event%3Apush)',['../index.html',1,'']]]
];
